### PR TITLE
Add text and link support

### LINKED ISSUE #16: Can't receive text and links on Mac
Description:
Can't receive text

image

The operation couldn't be completed.
(SwiftProtobuf.BinaryDecodingErrorerror3.)

Steps:
1. Copy any text or link
2. Click Share, Nearby share 
3. Click the NearDrop device
4. See error on Mac

### PR DESCRIPTION
**Pull request by krispykalsi**
Resolves #16 

Added two menu items that stay on by default.
Screenshot 2023-05-10 at 1 49 11 PM

### CODE REVIEW

**Comment by grishka** [comment]
I'm not sure I want any kind of action without user consent. This might be fine on a home network, but it has a lot of potential for abuse on any networks you don't manage — offices, coffee shops, etc. It would get worse when/if I add bluetooth support — your neighbors would gain the ability prank you too by sending you [this link](https://www.youtube.com/watch?v=dQw4w9WgXcQ). And I don't currently know how to reliably identify devices (device name is **not** a reliable identifier) to have a list of trusted devices that would have everything auto-accepted.

**Comment by tasomaniac** [comment]
I installed the app and sending a link was the first thing I tried to send. This would be an awesome addition.

About the "permisson". When sending files, NearDrop anyways send a notification to accept or reject. I would not add any new options at all and rely on this behavior. Meaning:

- If the content sent is a link: ask to accept or decline. If "accepted", open browser
- If the content send is a text: ask to accept or decline. if "accepted", copy to clipboard.

WDYT?

**Comment by tasomaniac** [comment]
As a user I would be fine. I don't think it is this tool's responsibility to check those things. As a user, if I click accept that means I recognize the sender.

**Comment by SurajMeena** [comment]
@krispykalsi Are you updating this PR with the changes discussed above? Just curious to have link and text sharing support in the neardrop releases

**Comment by SurajMeena** [comment]
I also wanted to know how is neardrop different from Soduto or KDE Connect for mac in terms of functionality. What additional things does it offer if we compare them? If nothing different or more advanced then what's the purpose of neardrop and Is it worth spending time on?

**Comment by victorigualada** [comment]
Hey @krispykalsi I built your branch but it's not working. I get the following error:

image

**Comment by RyadMM** [comment]
> Hey @krispykalsi I built your branch but it's not working. I get the following error when pasting text from the phone:
> 
> image

Hey, @victorigualada I was wondering if were you able to make the branch work.

Similarly to what @tasomaniac mentioned, I also installed exclusively the app as a workaround to quickly share link/clipboard from my phone, would love to make this work.

Thank you very much @grishka for the work you have done!

**Comment by krispykalsi** [comment]
Apologies for the late reply.

> Hey @krispykalsi I built your branch but it's not working. I get the following error when pasting text from the phone:
> 
> image

- Although this dialog appears, the content is copied correctly in the clipboard. Try pasting somewhere. 
- Also it happens randomly. Ignore the dialog and try sharing multiple times. You will notice that it does not show up every time.

I didn't have enough time to explore why it happens but I'll look into it as soon as I can.

**Comment by krispykalsi** [comment]
> @krispykalsi , @tasomaniac : Could you post a demonstration video of how it works?

There you go @Angelk90 

https://github.com/grishka/NearDrop/assets/10892504/c30cac60-4c68-4faf-8900-c7c44534f210

And on the mac -
- If it's a link, it opens up in the default browser
- If it's text, it is copied to the clipboard, and you just paste it.


> P.S. @krispykalsi : 
> Are you an android developer? 
> Have you ever done anything with android widgets?

I have experience in developing apps for both platforms in Swift, Kotlin and Flutter.
No, I haven't worked with widgets before. I'm open to trying it out though. What's on your mind?

**Comment by xygn** [comment]
@krispykalsi would it be possible for you to share the compiled package?

**Comment by JorisBodin** [comment]
> J'ai installé l'application et l'envoi d'un lien a été la première chose que j'ai essayé d'envoyer. Ce serait un ajout formidable.
> 
> A propos du "permis". Lors de l'envoi de fichiers, NearDrop envoie de toute façon une notification pour accepter ou rejeter. Je n'ajouterais aucune nouvelle option et je m'appuierais sur ce comportement. Signification:
> 
> * Si le contenu envoyé est un lien : demander d'accepter ou de refuser. Si "accepté", ouvrez le navigateur
> * Si le contenu envoyé est un SMS : demander d'accepter ou de refuser. si "accepté", copier dans le presse-papiers.
> 
> WDYT ?

That seems to me to be the ideal behavior
It's like sending a photo ...

**Comment by esterp** [comment]
This would be a great addition to the app.  Is there a reason why this change has not been merged?

**Comment by grishka** [comment]
> Is there a reason why this change has not been merged?

Yes, because not only does it add text and link support, it also adds the option to bypass the user consent which I'm very much against because of the great abuse potential.

**Comment by tasomaniac** [comment]
@grishka why don't you close it then?

I'm sure this can be implemented in a way that it is consistent with what Apple and Google are already doing. That should not introduce any privacy issues.

**Comment by JorisBodin** [comment]
> > Is there a reason why this change has not been merged?
> 
> Yes, because not only does it add text and link support, it also adds the option to bypass the user consent which I'm very much against because of the great abuse potential.

@grishka and if this is the behaviour as indicated in @tasomaniac's comment of 13 May?

**Comment by grishka** [comment]
Yes, that would work. Still not sure that text is to be copied into clipboard instead of saved in a file though.

**Comment by JorisBodin** [comment]
Yes, because it's currently displaying an error :(

We should be inspired by airdrop's behaviour...

**Comment by dgmltn** [comment]
How about doing it the same way as AirDrop? i.e., pop up a notification:

Untitled

**Comment by JorisBodin** [comment]
@grishka would a similar operation be possible?

**Comment by grishka** [comment]
I'm closing this because I did add support for links, and text is now properly rejected. Yes, the protocol has a specific error code for "attachment not supported" that I have neglected for all this time :)

As far as trusted devices go, I'm still not sure how to reliably identify devices. Either way, there needs to be a UI that would show a list of devices and allow removing ones you don't need. I'll add that when/if I find device identifiers.

**Comment by neorth** [comment]
I made a PR on @krispykalsi's branch that I have been running for a while. It has the UI you're requesting but uses the device name so could ofc be made up. I could open a new PR here if desired.

This is what it look like:
image

**Comment by neorth** [comment]
Here's the notification banner settings:
image

**Pull request closed without merging**
