### PR TITLE
Added remember device and always accept & Korean localization

### PR DESCRIPTION
**Pull request by fermata**
- Added remember device and always accept option
  - Distincts devices based on their names. So it may can cause security issue. (If sender uses same name)
  - Added user confirmation dialog before saving device so users can be cautious.
- Korean support

### CODE REVIEW

**Comment by grishka** [comment]
Device names aren't good enough identifiers. There's probably something that can help reliably identify devices in some of the mystery fields I currently ignore. Since I don't like half-measures, I don't want to merge this.

I can merge the Korean translation if you split it into a separate PR though.

**Comment by grishka** [comment]
Device names are **especially** bad as identifiers because by default the device name is just its model — so I imagine in the real world they aren't really that unique. You have to specifically go to settings and rename your device.

**Comment by fermata** [comment]
@grishka I have added a method using a MAC. How about this? It fetches arp cache on the background and uses IP address from TCP connection and matches the one on the cache to identify endpoint's MAC. (Since MAC can't be known on the original connection layer)

**Comment by IllusionVK** [comment]
I think it would be **very very very** handy to have the option to remember and device and always accept as an option.  If a user chooses to do this you could show them a dialog/popup and explain that it is a potential security risk as a device with the same name/same MAC could actually be a differnt device.  From my perspective this is the best of both worlds = give the user the education and allow them to make an informed decision.

From a risk management perspective any shared files should not be automatically executed by the operating system so the only risk is that someone could send me files that I don't want ? that seems like a pretty irrelevant risk to me (they could send me p*rn or fill up my hard drive (good luck) etc).  If they send malware as long as I don't execute it and there is no way for the OS to execute it automatically then it not a problem.

So hopefully you can see my perspective and agree that this is a major feature, as clicking every time to accept a file I just sent myself is a real drag.  BUT overall thanks for all of your work as well @grishka @fermata !

**Comment by IllusionVK** [comment]
Hey and I just downloaded and compiled from your repo @fermata and it rocks !!  no extra clicking needed, files just arrive on my mac so easily.  Thanks guys this is very helpful !

**Comment by grishka** [comment]
> I have added a method using a MAC

Still not sure I like this. This would break with dynamic MAC addresses that Android uses by default.
Screenshot_20230824-093915
And this *also* would break if I decide to add Bluetooth support since Bluetooth addresses are distinct from WiFi MAC addresses. IMO we need to find a way to determine proper device IDs from something in the protocol.

**Comment by grishka** [comment]
I'm closing this because I just merged #98.

**Pull request closed without merging**
