### PR TITLE
Add an ability to disable/enable NearDrop without exiting the app

### PR DESCRIPTION
**Pull request by vectro73**
[+] Add option to enable/disable NearDrop without exiting the app
[+] New menu item Enable NearDrop. Visible only when it was disabled
[+] New menu item Disable NearDrop. Visible only when it was enabled
[+] Visibility string in menu is now visible only when enabled
[+] Translations for 2 new menu items

### CODE REVIEW

**Comment by vectro73** [comment]
Hi, I have added an option to disable receiver without exiting the app. It works as following:
On the launch it is enabled. Option Disable NearDrop is visible in the menu. Once Disable selected, listener goes down and option Enable will appear in the menu. Once selected, listener starts. String Visible to everyone will only be displayed when receiver in the active status

**Comment by lucasmezencio** [comment]
Up

**Comment by grishka** [comment]
What "up"? Please don't annoy me.

**Comment by lucasmezencio** [comment]
@grishka I just saw this PR "stalled", and this is a feature that would be a nice to have, so I decided to ping you so it could be reviewed and merged.

I'm sorry if I "annoyed" you, I just wanted this feature to be added. This is an open source project, and @vectro73 did an amazing job here.

**Comment by grishka** [comment]
I don't intend to merge this because I don't want this feature.

See, the one thing I don't like about the open-source culture is that people would just come to your project, add some feature that you doesn't fit your vision, and then nag you to merge it. And if you refuse it, someone will inevitably get pissed off because "they worked on this, they put their time in, but you refused it, how dare you".

In my own projects, I don't really want any contributions beyond bug fixes and translations.

**Comment by lucasmezencio** [comment]
@grishka that's interesting. What's the point of making it open-source, then? To have people working for "free" so they can fix bugs you created yourself? Come on.

**Pull request closed without merging**
