### PR TITLE
Add StandWithUkraine banner

### PR DESCRIPTION
**Pull request by Turskyi**
This commit adds a banner to the README.md file to show support for Ukraine in its struggle against Russian aggression. The banner links to a website that provides information and resources on how to stand with Ukraine and help its people defend their sovereignty and democracy. The banner is a simple and effective way to raise awareness and solidarity among the GitHub community and beyond. I hope you will accept this pull request and join me in standing with Ukraine. Thank you.

### CODE REVIEW

**Comment by grishka** [comment]
While I am personally against this war and do stand with Ukraine (even though I am Russian living in Russia), I would prefer my software projects to not get political.

The readme is part of the technical documentation for this project. As with any documentation, its scope is only as wide as needed to describe what this app is, what it does, and how to use it. Societal issues lay outside of the scope of this project and its documentation.

Besides, that same readme says

> Pull requests that change the readme will not be accepted.

**Comment by Turskyi** [comment]
But that is your personal fault, because you are "_Russian living in Russia_", it is not politics killing Ukrainian citizens in Ukraine, those are same ordinary "Russians" like you.
 If you cannot even add a one line of code to your README, then you not only "_against_", you DO support the war, by keeping silence.

**Comment by grishka** [comment]
> But that is your personal fault

It is not. It is a common fallacy to blame ordinary people for what "their" government does. The Russian government does not have any feedback mechanisms left, and any, however small, acts of resistance are met with fiercest of punishments. Everyone already knows everything they want to know. There's no need to raise any additional awareness.

> If you cannot even add a one line of code to your README, then you not only "against", you DO support the war, by keeping silence.

How exactly would that make any difference? The AFU counteroffensive is ongoing. The military support from Western countries is pouring in. This is what matters. This is what decides the outcome of this war. People on Github adding banners to their readmes won't help anything. I don't believe in this kind of homeopathic activism.

**Comment by JesseCorbett** [comment]
@Turskyi my guy you're intentions are good but horribly misplaced. It's understandable for anyone to not want politics to get into their hobbies, and one relatively small repo not having a token banner of support isn't going to matter either way. I recommend you drop the topic.

**Pull request closed without merging**
