### PR TITLE
Add support for text and phone

### PR DESCRIPTION
**Pull request by d4rk-lucif3r**
Copy shared text to the pasteboard silently by @https://github.com/gramcraka

Original Contribution: https://github.com/grishka/NearDrop/pull/147

I just fixed issues with Enum Error and Other things. Have Done the validation

Here is how it handles the phone numbers and texts

### Phone
image

### Text
image

### CODE REVIEW

**Comment by grishka** [comment]
But what if I don't want this feature in this project?

**Comment by d4rk-lucif3r** [comment]
Haha..then It's up to you! Having this feature won't hurt. If anyone wants to use it, take it from my repo. I will create a release

**Comment by d4rk-lucif3r** [comment]
For anyone who is interested in trying out: https://github.com/d4rk-lucif3r/NearDrop/releases/tag/v0.1

Thanks @grishka

**Comment by Carniatto** [comment]
> For anyone who is interested in trying out: [d4rk-lucif3r/NearDrop@`v0.1` (release)](https://github.com/d4rk-lucif3r/NearDrop/releases/tag/v0.1)
> 
> Thanks @grishka

I've tried downloading your release, and it cannot be open, I'm running Sonoma

**Comment by d4rk-lucif3r** [comment]
> > For anyone who is interested in trying out: [d4rk-lucif3r/NearDrop@`v0.1` (release)](https://github.com/d4rk-lucif3r/NearDrop/releases/tag/v0.1)
> > Thanks @grishka
> 
> I've tried downloading your release, and it cannot be open, I'm running Sonoma

Hi, I can run it. I am also on Sonoma dev beta. Did you get any error while running?
image
image

**Comment by d4rk-lucif3r** [comment]
> > For anyone who is interested in trying out: [d4rk-lucif3r/NearDrop@`v0.1` (release)](https://github.com/d4rk-lucif3r/NearDrop/releases/tag/v0.1)
> > Thanks @grishka
> 
> I've tried downloading your release, and it cannot be open, I'm running Sonoma

Hi, 

Try this one: https://github.com/d4rk-lucif3r/NearDrop/releases/tag/v2.0.5

**Comment by Carniatto** [comment]
> > > For anyone who is interested in trying out: [d4rk-lucif3r/NearDrop@`v0.1` (release)](https://github.com/d4rk-lucif3r/NearDrop/releases/tag/v0.1)
> > > Thanks @grishka
> > 
> > 
> > I've tried downloading your release, and it cannot be open, I'm running Sonoma
> 
> Hi,
> 
> Try this one: [d4rk-lucif3r/NearDrop@`v2.0.5` (release)](https://github.com/d4rk-lucif3r/NearDrop/releases/tag/v2.0.5)

That works flawlessly <3

**Pull request closed without merging**
